### ISSUE TITLE
Installation error on microk8s on RHEL when running helm chart - Job in version "v1" cannot be handled as a Job: json: cannot unmarshal object into Go struct field PodSpec.spec.template.spec.serviceAccountName of type string

### ISSUE THREAD

**Issue by jezkerwin** [CybercentreCanada/assemblyline#151]
**Describe the bug**
I'm following the instructions for a micro8ks appliance located here https://cybercentrecanada.github.io/assemblyline4_docs/installation/appliance/kubernetes-microk8s/ 

I'm at the step to run the helm chart but getting the following error.

`Error: INSTALLATION FAILED: Job in version "v1" cannot be handled as a Job: json: cannot unmarshal object into Go struct field PodSpec.spec.template.spec.serviceAccountName of type string`

**To Reproduce**
1. all previous steps in the install guide were run successfully.
2. Execute the following command:
`sudo microk8s helm install assemblyline ~/git/assemblyline-helm-chart/assemblyline -f ~/git/deployment/values.yaml -n al`
3. Receive error immediately
`Error: INSTALLATION FAILED: Job in version "v1" cannot be handled as a Job: json: cannot unmarshal object into Go struct field PodSpec.spec.template.spec.serviceAccountName of type string`

**Expected behavior**
1. Command run successfully without error

**Screenshots**

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: v4.4.0
 - Browser: N/A
 - OS: RHEL 8.5

**Additional context**
I haven't adjusted any `values` or `secrets` as yet, I assumed the install instructions were good enough for a default test deployment.
I also ran the same steps on an Ubuntu 22.04 LTS VM and got the same error.

**Comment by jezkerwin** [comment]
I believe the issue is related to this reference in the helm chart. 

https://github.com/CybercentreCanada/assemblyline-helm-chart/blame/ac68808f4f916e35e82d4aa8897b4481b499c9b0/assemblyline/templates/jobs.yaml#L89 

Manually changing the file on my end appears to have solved my problem.

**Comment by cccs-rs** [comment]
Should be resolved in: https://github.com/CybercentreCanada/assemblyline-helm-chart/commit/6833c16f8aeb8d7abc774fa6798d58e6c1559900

**Comment by jezkerwin** [comment]
Thanks @cccs-rs I don't think it's fixed there might be something else going on, because now I'm getting the following error.

`[user@al4 git]$ sudo microk8s helm install --dry-run assemblyline ~/git/assemblyline-helm-chart/assemblyline -f ~/git/deployment/values.yaml -n al
Error: INSTALLATION FAILED: template: assemblyline/templates/jobs.yaml:90:36: executing "assemblyline/templates/jobs.yaml" at <.Values.unprivilegedServiceAccountName>: can't evaluate field Values in type interface {}`

**Comment by jezkerwin** [comment]
I think I might've figured it out. I think a `$` is missing from in front of the variable. in the jobs.yaml file

Broken:
`{{ .Values.unprivilegedServiceAccountName }}`

Fixed?
`{{ $.Values.unprivilegedServiceAccountName }}`
